### ISSUE TITLE
Prepare Fraunces for Google Fonts

### ISSUE THREAD

**Issue by arrowtype** [arrowtype/Fraunces#1]
Some of these fixes will follow the work from Viviana at https://github.com/vv-monsalve/Fraunces/issues/2

- [x] Update “Soften” axis to “Softness” and “Wonk” to “Wonkiness” to align with [axis registry](https://github.com/google/fonts/blob/0af700691cb9ad24372186d52bd9cd8c27550f1a/axisregistry/softness.textproto)
- [x] get static & variable fonts to build with expected family & style naming (ef8d2b815240f889b210e1c727c44b394ef6e746)
- [x] confirm axis names & defaults at https://github.com/undercasetype/Fraunces/issues/247; change if required
- [x] test gftools-packager for making a PR
- [x] change opsz default to min (https://github.com/undercasetype/Fraunces/issues/208)
- [x] Add step to build STAT table based on [Marc’s script for Roboto](https://github.com/TypeNetwork/Roboto/blob/05d39de057100d7db2bda636193c3abe5f7f9f47/scripts/gen_stat.py)
- [x] add ttfAutohint to venv, then rebuild with this. Also add to readme how to get this dependency. OR add gftools fix-nonhinting (I’ve done the latter, but I can change to add hinting if it is recommended)
- [x] get fraunces & fraunces italic working in the same font menu family
- [x] Probably: remove name IDs that are no longer needed due to simplified fvar
- [ ] check that Unicodes are correct for all glyphs – unsure what the best way to do this is ... maybe Marc’s OCR scripts?
- [ ] MAYBE: add a way to set font versions?
- [ ] MAYBE: abbreviate style naming to avoid exceeding 27 char length
- [x] MAYBE: change Softness style names to something alphabetical (https://github.com/undercasetype/Fraunces/issues/186)

Assumptions on naming:
- `WONK` axis name should be “Wonky”, per https://github.com/google/fonts/issues/2741
- `WONK` STAT names should be `Wonky` (elided) and `NonWonky` https://github.com/google/fonts/issues/2741#issuecomment-709463141
- `SOFT` axis instance names should be `Sharp`, `Soft`, & `ExtraSoft` (https://github.com/google/fonts/issues/2742)

## Fontbakery fixes
- [x] find out if it is okay to exceed 27 chars in variable font name
  - This probably won’t be relevant once the naming is fixed to reflect the default, simplified instance names

**Whitespace naming**
- [x] prevent `com.google.fonts/check/whitespace_glyphnames: Glyph 0x0020 is called "uni0020": Change to "space"` – probably by adding `--no-production-names` arg to fontmake

Now that I have added `--no-production-names`, I now get the message `* WARN: Glyph 0x00A0 is called "nbspace": Change to "uni00A0" [code: not-recommended-00a0]`. 

Not sure if this is worth worrying about...

**Optical size default must be 9pt**

- [x] `WARN: The "opsz" (Optical Size) coordinate on the "Regular" instance is recommended to be a value in the range 9 to 13. Got 144.0 instead.`
  - default for range set to `9`, but `mastering/scripts/removeUnwantedVFInstances.py` removes all instances but those with opsz=144... will investigate further
  - SOLVED by changing opsz values for final instances in variable designspaces

**Description length**

- [x] get shorter description or written exemption `FAIL: DESCRIPTION.en_us.html must have size smaller than 1000 bytes.` 
  – asked at https://github.com/undercasetype/Fraunces/issues/249

**` com.google.fonts/check/ligature_carets`** 

~~add ligature carets~~ Actually, I have added these to to UFOs, but ufo2ft doesn’t yet support this, so this is pointless. As was said at https://github.com/undercasetype/Fraunces/issues/206:

> Ligature carets are now included in the UFO spec, but I wasn’t able to find an indication that they are handled by ufo2ft or fontmake. related issue

Fontbakery false fails:

- `com.google.fonts/check/usweightclass – * FAIL: OS/2 usWeightClass is '900' when it should be '400'. [code: bad-value]` https://github.com/googlefonts/fontbakery/issues/2364

[WIP – more to come here]

**Comment by arrowtype** [comment]
Useful regex recipe to match & update UFO paths via find & replace:

`Fraunces9ptExtraSoft(.*?).ufo`
`Fraunces9ptS100$1.ufo`

> `.*` or `.*?`. The first one is greedy and will match till the last "sentence" in your string, the second one is lazy and will match till the next "sentence" in your string. [source](https://stackoverflow.com/a/6110113/3704306)

![image](https://user-images.githubusercontent.com/45946693/95889276-33a61800-0d50-11eb-91f3-cf1d339b2a3f.png)

**Comment by arrowtype** [comment]
"Italic" is in the family names in italic variable fonts.

- remove this

"None" is in static font family names for RIBBI fonts, due to a `try/except` block being used where it actually needs an `if/else` block.
